# Максимальное изменение угла в единицу времени
DELTA_ANGLE_THRESHOLD: 30
# Максимальное количество активных жестов, после чего сработает триггер
MAX_ACTIVE_GESTURES: 10
# Максимальное время наблюдения за человеком (в кадрах)
MAX_OBSERVATION_INTERVAL: 120
# Conf для ключевых точек человека
KEY_POINTS_CONFIDENCE: 0.5
