# Максимально допустимый угол в плечах, если руки вытянуты
SHOULDERS_ANGLE_THRESHOLD: 160
# Максимально допустимый угол в плечах, если человек сдается
SHOULDERS_BENT_ANGLE_THRESHOLD: 80
# Максимально допустимый угол в локтях, если человек сдается
ELBOW_BENT_ANGLE_THRESHOLD: 100
# Conf для ключевых точек человека
KEY_POINTS_CONFIDENCE: 0.5